language: php

php: 7.1

install:
  - composer install

before_script:
  - bash bin/install-wp-tests.sh wordpress_test root '' localhost

script:
  - vendor/bin/phpunit

after_success:
  - bash <(curl -s https://codecov.io/bash)